// Purchasing Webhooks
export const WEBHOOK_GET_BARANG = import.meta.env.VITE_WEBHOOK_GET_BARANG
export const WEBHOOK_INPUT_PO_V3 = import.meta.env.VITE_WEBHOOK_INPUT_PO_V3
export const WEBHOOK_LIST_PO = import.meta.env.VITE_WEBHOOK_LIST_PO
export const WEBHOOK_PAYMENT_PROOF = import.meta.env.VITE_WEBHOOK_PAYMENT_PROOF
export const WEBHOOK_STRUK_PEMBELIAN_KASPIN = import.meta.env.VITE_WEBHOOK_STRUK_PEMBELIAN_KASPIN
export const WEBHOOK_FINANCE_VERIF_PO = import.meta.env.VITE_WEBHOOK_FINANCE_VERIF_PO
export const WEBHOOK_INPUT_INVENTORY_REQUEST = import.meta.env.VITE_WEBHOOK_INPUT_INVENTORY_REQUEST
export const WEBHOOK_LIST_PENGAJUAN_INVENTARIS = import.meta.env.VITE_WEBHOOK_LIST_PENGAJUAN_INVENTARIS
export const WEBHOOK_LIST_PENGAJUAN_PERALATAN = import.meta.env.VITE_WEBHOOK_LIST_PENGAJUAN_PERALATAN
export const WEBHOOK_APPROVE_PENGAJUAN_PERALATAN = import.meta.env.VITE_WEBHOOK_APPROVE_PENGAJUAN_PERALATAN
export const WEBHOOK_LIST_INVENTARIS = import.meta.env.VITE_WEBHOOK_LIST_INVENTARIS
export const WEBHOOK_PAYMENT_PROOF_INVENTARIS = import.meta.env.VITE_WEBHOOK_PAYMENT_PROOF_INVENTARIS
export const WEBHOOK_GET_DATABASE_PERLENGKAPAN = import.meta.env.VITE_WEBHOOK_GET_DATABASE_PERLENGKAPAN
export const WEBHOOK_INPUT_PENGAJUAN_PERLENGKAPAN = import.meta.env.VITE_WEBHOOK_INPUT_PENGAJUAN_PERLENGKAPAN

// SPV Webhooks
export const SPV_WEBHOOK_GET_PO_LIST = import.meta.env.VITE_SPV_WEBHOOK_GET_PO_LIST
export const SPV_WEBHOOK_CONFIRM_PO = import.meta.env.VITE_SPV_WEBHOOK_CONFIRM_PO
export const SPV_WEBHOOK_SCAN_NOTA = import.meta.env.VITE_SPV_WEBHOOK_SCAN_NOTA
export const SPV_WEBHOOK_GET_PERALATAN_LIST = import.meta.env.VITE_SPV_WEBHOOK_GET_PERALATAN_LIST
export const SPV_WEBHOOK_CONFIRM_PERALATAN = import.meta.env.VITE_SPV_WEBHOOK_CONFIRM_PERALATAN

// SPV endpoints grouped for easy import
export const SPV_ENDPOINTS = {
  GET_PO_LIST: SPV_WEBHOOK_GET_PO_LIST,
  CONFIRM_PO: SPV_WEBHOOK_CONFIRM_PO,
  SCAN_NOTA: SPV_WEBHOOK_SCAN_NOTA,
  GET_PERALATAN_LIST: SPV_WEBHOOK_GET_PERALATAN_LIST,
  CONFIRM_PERALATAN: SPV_WEBHOOK_CONFIRM_PERALATAN,
}
